# example 1: https://gitlab.com/tkpapp/GitlabJuliaDemo.jl/-/blob/master/.gitlab-ci.yml
# example 2: https://gitlab.kuleuven.be/UCM/representativeperiodsfinder.jl/-/blob/dev/.gitlab-ci.yml
# `julia` images are from [Docker Hub: https://hub.docker.com/_/julia/

default:
  image: julia:latest
  before_script:
  # - apt-get -qq update; apt-get -y --no-install-recommends install git qt5-default
  - apt-get -qq update; apt-get -y install git
  - julia --project=@. -e "import Pkg; Pkg.build()" # build the package

test:latest:
  image: julia:latest
  script:
    - julia --project=@. -e "import Pkg; Pkg.test(; coverage=true)" # test package
    - julia --project=test/coverage -e 'import Pkg; Pkg.instantiate()' # setup coverage environment
    - julia --project=test/coverage test/coverage/coverage_summary.jl # run coverage summary
  coverage: '/Code coverage: \d+\.\d+/' # Regex expression to determine coverage
  only:
    - master

pages:
  stage: deploy
  script:
    # - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
    - julia --project=docs -e 'using Pkg; Pkg.develop(path=pwd()); Pkg.instantiate();' 
      # instantiate docs environment and dev the package to add it to environment
    - julia --project=docs --color=yes docs/make.jl # build docs
    - mv docs/build public # move to directory picked up by GitLab pages
  artifacts:
    paths:
      - public
  only:
    - master
