codecov:
  token: 326eed48-ecd2-4299-a8e6-75159f3c38e7

coverage:
  ignore:
    - "notebooks"
    - "readmes"
    - "runs"
    - "test"

  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch: no
    changes: no
