name: TagBot

on:
  schedule:
    - cron: 00 11 * * *

jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            ssh: ${{ secrets.DOCUMENTER_KEY }}
